### PR TITLE
Updated Dark Mode

### PR DESCRIPTION
**Pull request by KylixMedusa**
#74 Pull Request has been identified in this pull request and resolved by storing it in the local storage and retrieving using use Effect.

### CODE REVIEW

**Comment by shubhank-saxena** [comment]
Hey @KylixMedusa can you please correct all the travis failing tests and look for merge conflicts?

**Comment by KylixMedusa** [comment]
All merge conflicts are resolved. Could you merge it now?? Due to new hacktoberfest policies unmerged pull requests will not be counted.

**Comment by KylixMedusa** [comment]
There is no issue with the code and everything is working. I am not understanding the problem with Travis CI. There aren't any errors to be resolved

**Comment by shubhank-saxena** [comment]
Looks good @KylixMedusa  :rocket:

**Comment by shubhank-saxena** [comment]
Thank you @KylixMedusa for your contribution! Happy Hacktoberfest :heart:. Keep hacking!

**Pull request merged**
