### PR TITLE
Disables Caching

### LINKED ISSUE #111: Disable caching
This is a very lightweight app. We don't need caching in it. Disable it!

### PR DESCRIPTION
**Pull request by yubhav**
This fixes #111

### CODE REVIEW

**Comment by yubhav** [comment]
I did the pre-commit before pushing and it passed the checks but still there is an issue here. 
@shubhank-saxena @SabhyaGrover @payaljindal

**Comment by shubhank-saxena** [comment]
@yubhav run `pre-commit run --all` and push the changes that are made by the linter

**Comment by yubhav** [comment]
@shubhank-saxena Yes I did it!

**Comment by shubhank-saxena** [comment]
Okay. Just remove all conflicts and I will see the linting part issue!

**Comment by yubhav** [comment]
I've resolved the conflicts and the checks have passed!

**Comment by shubhank-saxena** [comment]
And it's done! :rocket:

**Comment by shubhank-saxena** [comment]
Thank you for your contribution @yubhav ! Happy Hacktoberfest :heart: Keep hacking!

**Pull request merged**
