### PR TITLE
Automatically adds http:// to the long url entered

### PR DESCRIPTION
**Pull request by agussetyar**
makes it easier for users to enter url without having to manually use http.

### CODE REVIEW

**Comment by shubhank-saxena** [comment]
@agussetyar thank you for your contribution. But won't it affect the https websites?

**Comment by agussetyar** [comment]
@shubhank-saxena  Usually on other shorturl sites out there, if the user does not use http or https in the entered url, it will automatically add http, even though the site should be https.

**Comment by shubhank-saxena** [comment]
> @shubhank-saxena Usually on other shorturl sites out there, if the user does not use http or https in the entered url, it will automatically add http, even though the site should be https.

Well, it does make sense. I mean if the website is https, the http will redirect to https.

**Comment by shubhank-saxena** [comment]
Thank you so much @agussetyar for your contribution. Happy Hacktoberfest :heart:. Keep hacking!

**Comment by agussetyar** [comment]
@shubhank-saxena Thanks!

**Comment by agussetyar** [comment]
Hi @shubhank-saxena,

Regarding updates to the Hacktoberfest rules. 
Can I ask permission to tag this pull-request with the label hacktoberfest?

thanks.

**Comment by shubhank-saxena** [comment]
Done @agussetyar !

**Comment by agussetyar** [comment]
@shubhank-saxena Thank you very much!

**Pull request merged**
