### PR TITLE
Scrolling down messes up UI

### LINKED ISSUE #82: Scrolling Down doesnt messes up UI
There is an issue with z-index.
image

### PR DESCRIPTION
**Pull request by ram170**
Fixes #82
Removed a duplicate function which was repeated twice.

**Bug:**

bug

**Fix:**

fix

### CODE REVIEW

**Comment by shubhank-saxena** [comment]
Hey @ram170 can I close this one if you are making changes on #82 ?

**Comment by ram170** [comment]
> 
> 
> Hey @ram170 can you close this one if you are making changes on #82 ?

@shubhank-saxena #82 is the issue. This is the PR for it. The changes are done here.

**Comment by shubhank-saxena** [comment]
> > Hey @ram170 can you close this one if you are making changes on #82 ?
> 
> @shubhank-saxena #82 is the issue. This is the PR for it. The changes are done here.

Ohh. I apologise for the confusion!

**Comment by shubhank-saxena** [comment]
Looks good to me :rocket:

**Comment by shubhank-saxena** [comment]
Thank you @ram170 for your contribution. Happy Hacktoberfest! :heart: Keep hacking!

**Pull request merged**
